/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Policy;

import Model.DatabaseConnection.DatabaseConnection;
import Model.Policy.Policy;
import Model.Policy.PolicyDirectory;
import java.awt.CardLayout;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABHINAVCHINTA
 */
public class Policy_Admin_Dashboard extends javax.swing.JPanel {

    private JPanel workPanel;
    private PolicyDirectory policyDirectory;

    /**
     * Creates new form Policy_Admin_Dashboard
     */
    public Policy_Admin_Dashboard(JPanel workPanel, PolicyDirectory policyDirectory) {
        initComponents();
        this.workPanel = workPanel;
        this.policyDirectory = policyDirectory;
        
        tblPolicyTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Policy ID", "Policy Name", "Claim Percentage", "Policy Amount", "Premium Amount", "Coverage Period", "Deductible Amount"
                }
        ));
        loadTableData();
        
         tblPolicyTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblPolicyTableMouseClicked(evt);
        }
    });

    }

    private void tblPolicyTableMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("Row clicked!");
        int selectedRow = tblPolicyTable.getSelectedRow();
        if (selectedRow != -1) {
            // Use the correct column indices to fetch data from the table
            txtPolicyName.setText(tblPolicyTable.getValueAt(selectedRow, 1).toString()); // Column 1: Policy Name
            txtClaimPercentage.setText(tblPolicyTable.getValueAt(selectedRow, 2).toString()); // Column 2: Claim Percentage
            txtPolicyamt.setText(tblPolicyTable.getValueAt(selectedRow, 3).toString()); // Column 3: Policy Amount
            txtPremiumAmt.setText(tblPolicyTable.getValueAt(selectedRow, 4).toString()); // Column 4: Premium Amount
            txtCoveragePeriod.setText(tblPolicyTable.getValueAt(selectedRow, 5).toString()); // Column 5: Coverage Period
            txtDeductibleAmt.setText(tblPolicyTable.getValueAt(selectedRow, 6).toString()); // Column 6: Deductible Amount
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPolicyName = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        lblClaimPercentage = new javax.swing.JLabel();
        txtClaimPercentage = new javax.swing.JTextField();
        lblPolicyAmt = new javax.swing.JLabel();
        txtPolicyamt = new javax.swing.JTextField();
        lblPremiumAmt = new javax.swing.JLabel();
        txtPremiumAmt = new javax.swing.JTextField();
        lblCoveragePeriod = new javax.swing.JLabel();
        txtCoveragePeriod = new javax.swing.JTextField();
        lblDeductibleAmt = new javax.swing.JLabel();
        txtDeductibleAmt = new javax.swing.JTextField();
        lblPolicyAdminDashboard = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolicyTable = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        lblPolicyName.setText("Policy Name");

        txtPolicyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPolicyNameActionPerformed(evt);
            }
        });

        lblClaimPercentage.setText("Claim Perecentage");

        txtClaimPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaimPercentageActionPerformed(evt);
            }
        });

        lblPolicyAmt.setText("Policy Amount");

        lblPremiumAmt.setText("Premium Amount");

        lblCoveragePeriod.setText("Coverage Period");

        lblDeductibleAmt.setText("Deductible Amount");

        lblPolicyAdminDashboard.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPolicyAdminDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPolicyAdminDashboard.setText("POLICY ADMIN DASHBOARD");

        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblPolicyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Policy Name", "Claim Percentage", "Policy Amount", "Premium Amount", "Coverage Period", "Deductable Amount"
            }
        ));
        jScrollPane1.setViewportView(tblPolicyTable);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/policyadmin.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout)
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(lblPolicyAdminDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPolicyName)
                            .addComponent(lblClaimPercentage)
                            .addComponent(lblPolicyAmt)
                            .addComponent(lblPremiumAmt)
                            .addComponent(lblCoveragePeriod)
                            .addComponent(lblDeductibleAmt)
                            .addComponent(btnAdd))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClaimPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPolicyamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPremiumAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCoveragePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeductibleAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtClaimPercentage, txtCoveragePeriod, txtDeductibleAmt, txtPolicyName, txtPolicyamt, txtPremiumAmt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)))
                .addComponent(lblPolicyAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicyName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClaimPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClaimPercentage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicyamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicyAmt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPremiumAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPremiumAmt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoveragePeriod)
                    .addComponent(txtCoveragePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeductibleAmt)
                    .addComponent(txtDeductibleAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtClaimPercentage, txtCoveragePeriod, txtDeductibleAmt, txtPolicyName, txtPolicyamt, txtPremiumAmt});

    }// </editor-fold>//GEN-END:initComponents

    private void txtPolicyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPolicyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPolicyNameActionPerformed

    private void txtClaimPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaimPercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaimPercentageActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        workPanel.remove(this);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.previous(workPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String policyName = txtPolicyName.getText();
            double claimPercentage = Double.parseDouble(txtClaimPercentage.getText());
            double policyAmount = Double.parseDouble(txtPolicyamt.getText());
            double premiumAmount = Double.parseDouble(txtPremiumAmt.getText());
            String coveragePeriod = txtCoveragePeriod.getText();
            double deductibleAmount = Double.parseDouble(txtDeductibleAmt.getText());

            Policy policy = new Policy(0, policyName, claimPercentage, policyAmount, premiumAmount, coveragePeriod, deductibleAmount);
            if (policyDirectory.addPolicy(policy)) {
                JOptionPane.showMessageDialog(this, "Policy added successfully!");
                loadTableData();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Error adding policy.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tblPolicyTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a policy to update.");
            return;
        }

        int policyId = (int) tblPolicyTable.getValueAt(selectedRow, 0);
        try {
            String policyName = txtPolicyName.getText();
            double claimPercentage = Double.parseDouble(txtClaimPercentage.getText());
            double policyAmount = Double.parseDouble(txtPolicyamt.getText());
            double premiumAmount = Double.parseDouble(txtPremiumAmt.getText());
            String coveragePeriod = txtCoveragePeriod.getText();
            double deductibleAmount = Double.parseDouble(txtDeductibleAmt.getText());

            Policy policy = new Policy(policyId, policyName, claimPercentage, policyAmount, premiumAmount, coveragePeriod, deductibleAmount);
            if (policyDirectory.updatePolicy(policy)) {
                JOptionPane.showMessageDialog(this, "Policy updated successfully!");
                loadTableData();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Error updating policy.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblPolicyTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a policy to delete.");
            return;
        }

        int policyId = (int) tblPolicyTable.getValueAt(selectedRow, 0);
        if (policyDirectory.deletePolicy(policyId)) {
            JOptionPane.showMessageDialog(this, "Policy deleted successfully!");
            loadTableData();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Error deleting policy.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tblPolicyTable.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Policy policy : policyDirectory.getAllPolicies()) {
            model.addRow(new Object[]{
                policy.getPolicyId(),
                policy.getPolicyName(),
                policy.getClaimPercentage(),
                policy.getPolicyAmount(),
                policy.getPremiumAmount(),
                policy.getCoveragePeriod(),
                policy.getDeductibleAmount()
            });
        }
    }

    private void clearFields() {
        txtPolicyName.setText("");
        txtClaimPercentage.setText("");
        txtPolicyamt.setText("");
        txtPremiumAmt.setText("");
        txtCoveragePeriod.setText("");
        txtDeductibleAmt.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClaimPercentage;
    private javax.swing.JLabel lblCoveragePeriod;
    private javax.swing.JLabel lblDeductibleAmt;
    private javax.swing.JLabel lblPolicyAdminDashboard;
    private javax.swing.JLabel lblPolicyAmt;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblPremiumAmt;
    private javax.swing.JTable tblPolicyTable;
    private javax.swing.JTextField txtClaimPercentage;
    private javax.swing.JTextField txtCoveragePeriod;
    private javax.swing.JTextField txtDeductibleAmt;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyamt;
    private javax.swing.JTextField txtPremiumAmt;
    // End of variables declaration//GEN-END:variables
}
