/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Main.LoginScreen;
import Main.InsuranceModel;
import Model.Account.Account;
import Model.New.Customer.Customer;
import Model.Customer.Policy.CustomerPolicy;
import Model.Customer.Policy.CustomerPolicyDirectory;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class CustomerMainScreen extends javax.swing.JPanel {

    /**
     * Creates new form CustomerMainScreen
     */
    JPanel workPanel;
    private Customer customer;

    public CustomerMainScreen(JPanel workPanel, Customer customer) {

        this.workPanel = workPanel;
        this.customer = customer;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClaimRequest = new javax.swing.JButton();
        btnBuyPolicy = new javax.swing.JButton();
        btnTransactionStatus = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("                                               Customer Portal");

        btnClaimRequest.setBackground(new java.awt.Color(204, 204, 204));
        btnClaimRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClaimRequest.setForeground(new java.awt.Color(0, 51, 153));
        btnClaimRequest.setText("Claim Request");
        btnClaimRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimRequestActionPerformed(evt);
            }
        });

        btnBuyPolicy.setBackground(new java.awt.Color(204, 204, 204));
        btnBuyPolicy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuyPolicy.setForeground(new java.awt.Color(0, 51, 153));
        btnBuyPolicy.setText("Buy Policy");
        btnBuyPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyPolicyActionPerformed(evt);
            }
        });

        btnTransactionStatus.setBackground(new java.awt.Color(204, 204, 204));
        btnTransactionStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTransactionStatus.setForeground(new java.awt.Color(0, 51, 153));
        btnTransactionStatus.setText("Transaction Status");
        btnTransactionStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionStatusActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setForeground(new java.awt.Color(0, 51, 153));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/figmacustomerdash.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClaimRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuyPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(225, 225, 225)
                                .addComponent(btnTransactionStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnLogout)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransactionStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuyPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnClaimRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        workPanel.remove(this);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.previous(workPanel);        // TODO add your handling code here:

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTransactionStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionStatusActionPerformed
        // TODO add your handling code here:
        // Create an instance of Transaction_Details and pass the customer object
        Transaction_Details transactionDetails = new Transaction_Details(workPanel, customer);
        workPanel.add("Transaction_Details", transactionDetails);

        // Switch to the Transaction_Details panel
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.show(workPanel, "Transaction_Details");

    }//GEN-LAST:event_btnTransactionStatusActionPerformed

    private void btnBuyPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyPolicyActionPerformed
        // TODO add your handling code here:
        AddVehiclePage addVehiclePage = new AddVehiclePage(workPanel, customer);
        workPanel.add("AddVehiclePage", addVehiclePage);

        // Switch to the AddVehiclePage
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.show(workPanel, "AddVehiclePage");

    }//GEN-LAST:event_btnBuyPolicyActionPerformed

    private void btnClaimRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimRequestActionPerformed
        // TODO add your handling code here:
        RenewalRequest claimRequest = new RenewalRequest(workPanel, customer);

        // Add the ClaimRequest panel to the workPanel
        workPanel.add("ClaimRequest", claimRequest);

        // Switch to the ClaimRequest panel
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.show(workPanel, "ClaimRequest");
    }//GEN-LAST:event_btnClaimRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyPolicy;
    private javax.swing.JButton btnClaimRequest;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTransactionStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
