/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Sales;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import UI.Sales.Sales_CallReport;
import UI.Sales.Sales_EmailRequest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Model.DatabaseConnection.DatabaseConnection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABHINAVCHINTA
 */
public class Sales_DashBoard extends javax.swing.JPanel {

    /**
     * Creates new form Sales_DashBoard
     */
    JPanel workPanel;
    String selectedCustomerName;
    String selectedCustomerEmail;

    public Sales_DashBoard(JPanel workPanel) {
        initComponents();
        this.workPanel = workPanel;
        loadCustomerData();
        tblCustomerDetails.getSelectionModel().addListSelectionListener(event -> {
            int selectedRow = tblCustomerDetails.getSelectedRow();
            if (selectedRow >= 0) {
                selectedCustomerName = tblCustomerDetails.getValueAt(selectedRow, 1).toString();
                selectedCustomerEmail = tblCustomerDetails.getValueAt(selectedRow, 3).toString();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerDetails = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        btnCallReport = new javax.swing.JButton();
        btnAddCallReport = new javax.swing.JButton();
        btnEmailRequest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales Person Dashboard");

        tblCustomerDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "FirstName", "Username", "Email", "Phone_No"
            }
        ));
        jScrollPane1.setViewportView(tblCustomerDetails);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCallReport.setText("Call Report");
        btnCallReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallReportActionPerformed(evt);
            }
        });

        btnAddCallReport.setText("Add Call Report");
        btnAddCallReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCallReportActionPerformed(evt);
            }
        });

        btnEmailRequest.setText("Email Request");
        btnEmailRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailRequestActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer Details");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/salesman.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddCallReport)
                .addGap(50, 50, 50)
                .addComponent(btnEmailRequest)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnLogout)
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCallReport)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnLogout)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCallReport)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCallReport)
                    .addComponent(btnEmailRequest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        workPanel.remove(this);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.previous(workPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCallReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallReportActionPerformed
        // TODO add your handling code here:
        Sales_ViewCallReportDetails emailRequest = new Sales_ViewCallReportDetails(workPanel);

        // Add Email Request panel with a unique name
        workPanel.add("Sales_ViewCallRequest", emailRequest);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.show(workPanel, "Sales_ViewCallRequest");
    }//GEN-LAST:event_btnCallReportActionPerformed

    private void btnAddCallReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCallReportActionPerformed
        // TODO add your handling code here:
        if (selectedCustomerName == null || selectedCustomerEmail == null) {
            JOptionPane.showMessageDialog(this, "Please select a customer first.");
            return;
        }
        Sales_CallReport callReport = new Sales_CallReport(workPanel, selectedCustomerName, selectedCustomerEmail);

        // Add Call Report panel with a unique name
        workPanel.add("Sales_CallReport", callReport);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.show(workPanel, "Sales_CallReport");
    }//GEN-LAST:event_btnAddCallReportActionPerformed

    private void btnEmailRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailRequestActionPerformed
        // TODO add your handling code here:
        if (selectedCustomerName == null || selectedCustomerEmail == null) {
            JOptionPane.showMessageDialog(this, "Please select a customer first.");
            return;
        }
        Sales_EmailRequest emailRequest = new Sales_EmailRequest(workPanel, selectedCustomerName, selectedCustomerEmail);

        // Add Email Request panel with a unique name
        workPanel.add("Sales_EmailRequest", emailRequest);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.show(workPanel, "Sales_EmailRequest");
    }//GEN-LAST:event_btnEmailRequestActionPerformed
    private void loadCustomerData() {
        DefaultTableModel model = (DefaultTableModel) tblCustomerDetails.getModel();
        model.setRowCount(0); // Clear existing rows
        String query = "SELECT customer_id, first_name, username, email, phone FROM customers";

        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(query); ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("customer_id"),
                    rs.getString("first_name"),
                    rs.getString("username"),
                    rs.getString("email"),
                    rs.getString("phone")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching customer data.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCallReport;
    private javax.swing.JButton btnCallReport;
    private javax.swing.JButton btnEmailRequest;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomerDetails;
    // End of variables declaration//GEN-END:variables
}
