/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Model.Account.Account;
import Model.Account.AccountCredentials;
import Model.Account.AccountCredentialsDirectory;
import Model.Customer.Customer;
import Model.DatabaseConnection.DatabaseConnection;
import Model.Policy.PolicyDirectory;
import UI.ClaimProcessor.Claim_Processor_Dashboard;
import UI.Comp.Admin.AdminMainScreen;
import UI.Comp.Agent.AgentMainScreen;
import UI.Customer.CustomerLogin;
import UI.Customer.CustomerMainScreen;
import UI.IT_Support.IT_Support_Dashboard;
import UI.Thirdparty.PAYMENT.VerifySyncBillingLogin;
import UI.Thirdparty.PAYMENT.VerifySyncBillingMainPage;
import UI.Thirdparty.POLK.POLKChoiceScreen;
import UI.Thirdparty.POLK.POLKLoginScreen;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import UI.IT_Support.IT_Support_Tech_Isuue_Homepage;
import UI.Policy.Policy_Admin_Dashboard;
import UI.Sales.Sales_DashBoard;

/**
 *
 * @author kishorebalaji
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    InsuranceModel BIM;
    JPanel workPanel;

    public LoginScreen(InsuranceModel BIM, JPanel workPanel) {
        initComponents();
        this.BIM = BIM;
        this.workPanel = workPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnPOLK = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnverifybilling1 = new javax.swing.JButton();
        btnCustomersLogin = new javax.swing.JButton();
        btnTechnicalIssue = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Insurance_Management_Services.jpg"))); // NOI18N

        jLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel.setForeground(new java.awt.Color(51, 51, 51));
        jLabel.setText("        User Login ");

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(51, 51, 51));
        lblUserName.setText("User Name: ");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblPassword.setText("Password: ");

        btnLogin.setBackground(new java.awt.Color(0, 51, 153));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Hebrew", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("      Third-Party Logins");

        btnPOLK.setForeground(new java.awt.Color(51, 51, 51));
        btnPOLK.setText("POLK");
        btnPOLK.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        btnPOLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOLKActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Hebrew", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Customer Login");

        btnverifybilling1.setForeground(new java.awt.Color(51, 51, 51));
        btnverifybilling1.setText("Verify Billing");
        btnverifybilling1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        btnverifybilling1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifybilling1ActionPerformed(evt);
            }
        });

        btnCustomersLogin.setForeground(new java.awt.Color(51, 51, 51));
        btnCustomersLogin.setText("Customer Login");
        btnCustomersLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        btnCustomersLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersLoginActionPerformed(evt);
            }
        });

        btnTechnicalIssue.setText("Technical Issue");
        btnTechnicalIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTechnicalIssueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 126, Short.MAX_VALUE)))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTechnicalIssue)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPOLK, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(375, 375, 375)
                                .addComponent(btnverifybilling1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(btnCustomersLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(522, 522, 522)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnTechnicalIssue)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCustomersLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPOLK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnverifybilling1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String userID = txtUserName.getText();
    String password = txtPassword.getText();

    try (Connection conn = DatabaseConnection.getConnection()) {
        String query = "SELECT role, password, username FROM users WHERE username = ?";
        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, userID);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    String storedPassword = rs.getString("password");
                    String role = rs.getString("role");

                    // Verify the password
                    if (storedPassword.equals(password)) {
                        txtUserName.setText("");
                        txtPassword.setText("");

                        // Retrieve account object based on username
                        Account account = BIM.getAccountDirectory().findAccountByUserID(userID);

                        CardLayout layout = (CardLayout) workPanel.getLayout();

                        switch (role.toLowerCase()) {
                            case "admin":
                                AdminMainScreen adminMainScreen = new AdminMainScreen(BIM, workPanel, account);
                                workPanel.add("AdminMainScreen", adminMainScreen);
                                layout.next(workPanel);
                                break;
                            case "agent":
                                    AgentMainScreen agentMainScreen = new AgentMainScreen(BIM, workPanel);
                                    workPanel.add("AgentMainScreen", agentMainScreen);
                                    layout.next(workPanel);
                                break;
                            case "itsupport":
                                IT_Support_Dashboard itSupportDashboard = new IT_Support_Dashboard(workPanel);
                                workPanel.add("ITSupportDashboard", itSupportDashboard);
                                layout.next(workPanel);
                                break;
                            case "policyadmin": 
                                PolicyDirectory policyDirectory = new PolicyDirectory();
                                Policy_Admin_Dashboard policyAdminDashboard = new Policy_Admin_Dashboard(workPanel, policyDirectory);
                                workPanel.add("PolicyAdminDashboard", policyAdminDashboard);
                                layout.next(workPanel);
                                break;
                            case "salesperson": 
                                Sales_DashBoard salesDashboard = new Sales_DashBoard(workPanel);
                                workPanel.add("SalesDashboard", salesDashboard);
                                layout.next(workPanel);
                                break;
                            case "claimprocessor": // Add Claim Processor role
                                Claim_Processor_Dashboard claimProcessorDashboard = new Claim_Processor_Dashboard(workPanel);
                                workPanel.add("ClaimProcessorDashboard", claimProcessorDashboard);
                                layout.next(workPanel);
                                break;
                            default:
                                JOptionPane.showMessageDialog(this, "Unknown role.");
                                break;
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Password");
                        txtPassword.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "User not found");
                    txtPassword.setText("");
                }
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error connecting to the database");
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnPOLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOLKActionPerformed
        // Instantiate the POLKLoginScreen panel and pass BIM and workPanel
        POLKLoginScreen polkLoginScreen = new POLKLoginScreen(workPanel);

        // Add the POLKLoginScreen panel back to the workPanel
        workPanel.add("POLKLoginScreen", polkLoginScreen);

        // Switch to the POLKLoginScreen panel
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.show(workPanel, "POLKLoginScreen");

    }//GEN-LAST:event_btnPOLKActionPerformed

    private void btnverifybilling1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifybilling1ActionPerformed
        // TODO add your handling code here:
        VerifySyncBillingLogin verifySyncBillingLogin = new VerifySyncBillingLogin(BIM, workPanel);
        workPanel.add("VerifySyncBillingLogin", verifySyncBillingLogin);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);
    }//GEN-LAST:event_btnverifybilling1ActionPerformed

    private void btnCustomersLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersLoginActionPerformed
        // TODO add your handling code here:

        // Find the account by userID
        // Create and navigate to the CustomerMainScreen
        CustomerLogin customerLogin = new CustomerLogin(workPanel);
        workPanel.add("CustomerLogin", customerLogin);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);

    }//GEN-LAST:event_btnCustomersLoginActionPerformed

    private void btnTechnicalIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTechnicalIssueActionPerformed
        // TODO add your handling code here:
        IT_Support_Tech_Isuue_Homepage itSupport = new IT_Support_Tech_Isuue_Homepage(workPanel);

        // Add the new panel to the workPanel
        workPanel.add("ItSupport", itSupport);

        // Switch to the new panel
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);
    }//GEN-LAST:event_btnTechnicalIssueActionPerformed
    private javax.swing.JButton btnCustomerLogin;
    private javax.swing.JButton btnSalespersonLogin;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomersLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPOLK;
    private javax.swing.JButton btnTechnicalIssue;
    private javax.swing.JButton btnverifybilling1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
