/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.IT_Support;

import javax.swing.JPanel;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import Model.DatabaseConnection.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;

/**
 *
 * @author ABHINAVCHINTA
 */
public class IT_Support_Tech_Isuue_Homepage extends javax.swing.JPanel {

    JPanel workPanel;

    public IT_Support_Tech_Isuue_Homepage(JPanel workPanel) {
        initComponents();
        this.workPanel = workPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblReportTechnicalIssue = new javax.swing.JLabel();
        txtReportanissue = new javax.swing.JTextField();
        lblReportAnIssue = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblEnterYourEmail = new javax.swing.JLabel();
        txtEnterYourEmail = new javax.swing.JTextField();
        txtEnterYourName = new javax.swing.JTextField();
        lblEnterYourName1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblReportTechnicalIssue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReportTechnicalIssue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportTechnicalIssue.setText("Report Technical Issue");

        txtReportanissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportanissueActionPerformed(evt);
            }
        });

        lblReportAnIssue.setText("Report An Issue");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblEnterYourEmail.setText("Enter your Email");

        txtEnterYourEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterYourEmailActionPerformed(evt);
            }
        });

        txtEnterYourName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterYourNameActionPerformed(evt);
            }
        });

        lblEnterYourName1.setText("Enter your Name");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/technical.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblReportTechnicalIssue, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSubmit)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblReportAnIssue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtReportanissue, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEnterYourEmail)
                                    .addComponent(lblEnterYourName1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnterYourName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnterYourEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(150, 150, 150)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReportTechnicalIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterYourName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterYourName1))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterYourEmail)
                    .addComponent(txtEnterYourEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportAnIssue)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtReportanissue, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workPanel.remove(this);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.previous(workPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        // Get inputs
        // Get inputs
        String name = txtEnterYourName.getText().trim();
        String email = txtEnterYourEmail.getText().trim();
        String reason = txtReportanissue.getText().trim();
        String stage = "submitted"; // Default stage

        // Validate inputs
        if (name.isEmpty() || email.isEmpty() || reason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Database query
        String query = "INSERT INTO technical_issue (name, email, reason, stage) VALUES (?, ?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(query)) {

            // Set parameters
            stmt.setString(1, name);
            stmt.setString(2, email);
            stmt.setString(3, reason);
            stmt.setString(4, stage);

            // Execute the query
            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Issue reported successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

                // Send email notification
                sendEmail(email, name, reason, stage);

                // Clear the fields after successful submission
                txtEnterYourName.setText("");
                txtEnterYourEmail.setText("");
                txtReportanissue.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to report the issue. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtEnterYourEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterYourEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterYourEmailActionPerformed

    private void txtEnterYourNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterYourNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterYourNameActionPerformed

    private void txtReportanissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportanissueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportanissueActionPerformed
    private void sendEmail(String recipientEmail, String recipientName, String reason, String stage) {
        final String senderEmail = "rajumighty432@gmail.com"; // Replace with your email
        final String senderPassword = "bqff vybd eclw pxdf"; // Replace with your App Password

        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        properties.put("mail.smtp.ssl.protocols", "TLSv1.2");

        Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(senderEmail, senderPassword);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(senderEmail));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recipientEmail));
            message.setSubject("Technical Issue Reported");

            // Email content with details
            message.setText(
                    "Dear " + recipientName + ",\n\n"
                    + "Your technical issue has been successfully reported.\n\n"
                    + "Details:\n"
                    + "Name: " + recipientName + "\n"
                    + "Reason: " + reason + "\n"
                    + "Stage: " + stage + "\n\n"
                    + "Our team will address this issue shortly.\n\n"
                    + "Regards,\n"
                    + "Admin Team"
            );

            Transport.send(message);
            JOptionPane.showMessageDialog(this, "Email sent to " + recipientEmail);
        } catch (MessagingException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to send email: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnterYourEmail;
    private javax.swing.JLabel lblEnterYourName1;
    private javax.swing.JLabel lblReportAnIssue;
    private javax.swing.JLabel lblReportTechnicalIssue;
    private javax.swing.JTextField txtEnterYourEmail;
    private javax.swing.JTextField txtEnterYourName;
    private javax.swing.JTextField txtReportanissue;
    // End of variables declaration//GEN-END:variables
}
